import 'package:hive/hive.dart';

part 'contact.g.dart';  // This file is generated by Hive generator

@HiveType(typeId: 0)
class Contact {
  @HiveField(0)
  final String id;

  @HiveField(1)
  final String name;

  @HiveField(2)
  String avatarUrl = '';

  Contact({required this.id, required this.name, String? avatarUrl}) {
    this.avatarUrl = 'https://via.placeholder.com/150/0000FF/808080?Text=${name[0]}';
  }
}

